-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 16:01:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema anicoboard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anicoboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anicoboard` DEFAULT CHARACTER SET utf8 ;
USE `anicoboard` ;

-- -----------------------------------------------------
-- Table `anicoboard`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anicoboard`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `usericon` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `anicoboard`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anicoboard`.`articles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `article` TEXT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_articles_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_articles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `anicoboard`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `anicoboard`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anicoboard`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(255) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `articles_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_users1_idx` (`users_id` ASC),
  INDEX `fk_comments_articles1_idx` (`articles_id` ASC),
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `anicoboard`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `anicoboard`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `anicoboard`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anicoboard`.`likes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `like` TINYINT(10) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,
  `articles_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_likes_users1_idx` (`users_id` ASC),
  INDEX `fk_likes_articles1_idx` (`articles_id` ASC),
  CONSTRAINT `fk_likes_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `anicoboard`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `anicoboard`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `anicoboard`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anicoboard`.`pictures` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `src` VARCHAR(255) NOT NULL,
  `articles_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pictuers_articles1_idx` (`articles_id` ASC),
  CONSTRAINT `fk_pictuers_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `anicoboard`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `anicoboard`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anicoboard`.`follows` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `follower` INT(100) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `articles_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_follows_users1_idx` (`users_id` ASC),
  INDEX `fk_follows_articles1_idx` (`articles_id` ASC),
  CONSTRAINT `fk_follows_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `anicoboard`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follows_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `anicoboard`.`articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
